### ISSUE TITLE
Nefunkční na Firefox for Android

### ISSUE THREAD

**Issue by DangeMask** [tonyno/wordle-czech#4]
Originální Wordle sjíždím na Firefoxu na mobilu, teď jsem s radostí narazil i na tuto českou verzi, ale ta mi zobrazí jen prázdné bílé pole.

Když přepnu na "verzi pro počítač", tak se zobrazí, jen samozřejmě v původním "velkém" rozlišení, které je na mobilu trochu nepraktické.
Zkoušel jsem i mobilní Edge a ten vypadá v pořádku.

Screenshoty:
Firefox v mobilním zobrazení:
![Screenshot_20220116-150418_Firefox](https://user-images.githubusercontent.com/47944010/149663385-c144c859-abb6-4230-a5fd-a849bb313a38.jpg)

Firefox v desktop zobrazení (Edge v desktop zobrazení vypadá podobně):
![Screenshot_20220116-150459_Firefox](https://user-images.githubusercontent.com/47944010/149663416-21237302-f0f7-43d0-8af4-af18005353a1.jpg)

Edge v mobilním zobrazení:
![Screenshot_20220116-150507_Edge](https://user-images.githubusercontent.com/47944010/149663437-44303666-727d-4f49-839e-f60fea598f95.jpg)

**Comment by tonyno** [comment]
@DangeMask , muzete to prosim zkusit znovu a dat Refresh stranky pripadne Anonymni okno pro pokus? Mel jsem tam chybu ktera se projevovala presne stejne v Safari. Ted uz by melo byt opraveno. https://hadejslova.cz/

**Comment by DangeMask** [comment]
Díky za rychlou reakci. Zkusil jsem refresh, anonymní režim a pro jistotu i restart telefonu, ale chová se to pořád stejně :-(
Ještě pro jistotu doplním:
Firefox 95.2.0
Android 11
Samsung A52s 5G

**Comment by tonyno** [comment]
@DangeMask , dík moc, jste zlatej. Podívám se na to. Dík moc.

**Comment by DangeMask** [comment]
Sám jsem programátor, takže vím, jak je pro debugging důležitý co nejpřesnější popis podmínek :-)
Kdyby bylo potřeba cokoli otestovat, dejte vědět.

**Comment by tonyno** [comment]
@DangeMask , tak pozivitní je, že se mi chyba vyskytuje ve Firefoxu taky. Ten jsem nikdy na mobilu nepoužíval, proto jsem si toho nevšiml. Zkoumám jaké jsou možnosti debuggingu na Androidu. No není to peříčko. Dám vědět, Dík.

**Comment by tonyno** [comment]
@DangeMask , opraveno a retestovano. Zkuste prosim jestli uz funguje i u vas. Dik moc.

**Comment by DangeMask** [comment]
Funguje!
Pro jistotu jsem otestoval i v anonymním režimu, abych mohl znovu "hádat". A za mě vše funguje.

Díky moc. 👌
![20220118_083131](https://user-images.githubusercontent.com/47944010/149890904-ecc7ead6-fa13-4079-9da2-42786434aed7.jpg)

**Comment by DangeMask** [comment]
Jen zajímavost: V Edge je navíc v "blahopřejném" okně tlačítko "Sdílet", které ve FF chybí... ale to už je fakt detail :-)
